/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as JuntosRouteImport } from './routes/juntos'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LerBookChapterRouteImport } from './routes/ler.$book.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const JuntosRoute = JuntosRouteImport.update({
  id: '/juntos',
  path: '/juntos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LerBookChapterRoute = LerBookChapterRouteImport.update({
  id: '/ler/$book/$chapter',
  path: '/ler/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/conquistas': typeof ConquistasRoute
  '/entrar': typeof EntrarRoute
  '/juntos': typeof JuntosRoute
  '/plano': typeof PlanoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/ler/$book/$chapter': typeof LerBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/conquistas': typeof ConquistasRoute
  '/entrar': typeof EntrarRoute
  '/juntos': typeof JuntosRoute
  '/plano': typeof PlanoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/ler/$book/$chapter': typeof LerBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/conquistas': typeof ConquistasRoute
  '/entrar': typeof EntrarRoute
  '/juntos': typeof JuntosRoute
  '/plano': typeof PlanoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/ler/$book/$chapter': typeof LerBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/auth'
    | '/conquistas'
    | '/entrar'
    | '/juntos'
    | '/plano'
    | '/redefinir-senha'
    | '/ler/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/auth'
    | '/conquistas'
    | '/entrar'
    | '/juntos'
    | '/plano'
    | '/redefinir-senha'
    | '/ler/$book/$chapter'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/auth'
    | '/conquistas'
    | '/entrar'
    | '/juntos'
    | '/plano'
    | '/redefinir-senha'
    | '/ler/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AuthRoute: typeof AuthRoute
  ConquistasRoute: typeof ConquistasRoute
  EntrarRoute: typeof EntrarRoute
  JuntosRoute: typeof JuntosRoute
  PlanoRoute: typeof PlanoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  LerBookChapterRoute: typeof LerBookChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juntos': {
      id: '/juntos'
      path: '/juntos'
      fullPath: '/juntos'
      preLoaderRoute: typeof JuntosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ler/$book/$chapter': {
      id: '/ler/$book/$chapter'
      path: '/ler/$book/$chapter'
      fullPath: '/ler/$book/$chapter'
      preLoaderRoute: typeof LerBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AuthRoute: AuthRoute,
  ConquistasRoute: ConquistasRoute,
  EntrarRoute: EntrarRoute,
  JuntosRoute: JuntosRoute,
  PlanoRoute: PlanoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  LerBookChapterRoute: LerBookChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
